# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09cd06af58bde38601c2b30769f5bc3dc653183ca416b80acb6cf5fdbfba938356a6231a8d9cefab7b26fbff3eb701bba211387b2e382877e8b08efc7d76be59

test:
  secret_key_base: ef29f2a192eee9bf125a09b76551636e1435abac4d8502ab1a5c921cb098f4e0103f2d84afc714e6a8473a8d37b5b2e576b34173a51347f59d4bbe696431fc3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
