# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c61a9ec55e45b8a6d219fa950049a95da9115dfee799802616e680eddc56e6565e785c8e88786cb6b3a56463955e1034281e2a647601ccb8882c550bf44517d

test:
  secret_key_base: 52772a678c221133812a86a21175916fe610aad28847475d10d64ad13cf761a59f1248dfbcb809c68a25be90fd54a6d3cc12a114ae7c0704c16933d267df8226

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
